version: '3'

services:
  backend:
    build:
      context: ./backend
      args:
        env: "dev"
    volumes:
      - ./backend:/usr/src/app:z
    ports:
      - 8001:3000
    environment:
      - ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@postgres/icetrap
      - SECRET_KEY=hunter2
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        env: "dev"
    environment:
      - ENV=dev
    volumes:
      - ./frontend:/usr/src/app:z
      - /usr/src/app/node_modules
    stdin_open: true
    ports:
      - 8002:3000

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:14
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=icetrap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
